# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WageKeeper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '10.0'
  use_frameworks!

  # Pods for WageKeeper
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'KTLoadingLabel'
  pod 'EMSpinnerButton'
  pod 'PasswordTextField'


end
